site_name: Practica IAW Mkdocs

nav:
    - Principal: index.md
    - Acerca de: about.md
    - Practica 5.1: practica5.1.md
    - Practica 5.2: practica5.2.md

theme: 
    name: material
    palette:
        primary: orange
        accent: deep orange